name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          args: "-g -pdf -file-line-error -halt-on-error -interaction=nonstopmode"
          root_file: |
            main.tex
            main-frn.tex
            main.tex
            
      - name: Upload to Netlify     
        uses: MrFlynn/upload-to-netlify-action@v2
        with:
          source-file: "main.pdf"
          destination-path: "/main.pdf"
          site-name: quantum-search-algorithm
          netlify-token: ${{ secrets.NETLIFY_TOKEN }}
          
