name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
  
      - name: Upload
        run: |
          # configure git
          git config --global user.name "Francesco Pinzauti"
          git config --global user.email "git@francescopinzauti.me"
          # setup ssh
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          git clone --depth=1 --branch gh-pages git@github.com:Pinzauti/quantum-search-algorithm.git "$GITHUB_WORKSPACE/deploy"
          cp -f example/main.pdf "$GITHUB_WORKSPACE/deploy/main.pdf"
          cd "$GITHUB_WORKSPACE/deploy"
          git add main.pdf
          git commit -m "[github actions] deploy"
          git push
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
